export const allData = [
  {
    backgroundColor: "#42CAFD",
    color: "black",
    text: "Music",
    id: "music",
    entries: ["Kindle like sheet music"],
  },
  {
    backgroundColor: "#66B3BA",
    color: "black",
    text: "Programming",
    id: "programming",
    entries: ["Make setting up enviornment easiar"],
  },
  {
    backgroundColor: "#8EB19D",
    color: "black",
    text: "Physics",
    id: "physics",
    entries: ["Invert waves to cancel out all irritating sounds"],
  },
  // {
  //   backgroundColor: "#F6EFA6",
  //   color: "black",
  //   text: "Movies",
  //   id: "movies",
  //   entries: [],
  // },
  // {
  //   backgroundColor: "#F0D2D1",
  //   color: "black",
  //   text: "Chores",
  //   id: "chores",
  //   entries: [],
  // },
  // {
  //   backgroundColor: "#42CAFD",
  //   color: "black",
  //   text: "To-Do",
  //   id: "todo",
  //   entries: [],
  // },
  // {
  //   backgroundColor: "#66B3BA",
  //   color: "black",
  //   text: "Business Club",
  //   id: "business",
  //   entries: [],
  // },
  // {
  //   backgroundColor: "#8EB19D",
  //   color: "black",
  //   text: "Drink Concoctions",
  //   id: "drinks",
  //   entries: [],
  // },
  // {
  //   backgroundColor: "#F6EFA6",
  //   color: "black",
  //   text: "Life",
  //   id: "life",
  //   entries: [],
  // },
  // {
  //   backgroundColor: "#F0D2D1",
  //   color: "black",
  //   text: "Ideas",
  //   id: "ideas",
  //   entries: [],
  // },
  // {
  //   backgroundColor: "#42CAFD",
  //   color: "black",
  //   text: "Etc.",
  //   id: "etc",
  //   entries: [],
  // },
];
